import type { IndicatorEngine } from './IndicatorEngine.js';
// Overlays
import { SMAIndicator } from './overlay/SMA.js';
import { EMAIndicator } from './overlay/EMA.js';
import { BollingerBandsIndicator } from './overlay/BollingerBands.js';
import { VWAPIndicator } from './overlay/VWAP.js';
import { IchimokuIndicator } from './overlay/Ichimoku.js';
import { ParabolicSARIndicator } from './overlay/ParabolicSAR.js';
import { SupertrendIndicator } from './overlay/Supertrend.js';
import { KeltnerChannelIndicator } from './overlay/KeltnerChannel.js';
import { DonchianChannelIndicator } from './overlay/DonchianChannel.js';
import { PivotPointsIndicator } from './overlay/PivotPoints.js';
import { AnchoredVWAPIndicator } from './overlay/AnchoredVWAP.js';
import { ZigZagIndicator } from './overlay/ZigZag.js';
import { LinearRegressionChannelIndicator } from './overlay/LinearRegressionChannel.js';
import { HullMAIndicator } from './overlay/HullMA.js';
import { MTFMovingAverageIndicator } from './overlay/MTFMovingAverage.js';
import { SessionVWAPIndicator } from './overlay/SessionVWAP.js';
import { ChandelierExitIndicator } from './overlay/ChandelierExit.js';
import { AlligatorIndicator } from './overlay/Alligator.js';
import { VWMAIndicator } from './overlay/VWMA.js';
import { WMAIndicator } from './overlay/WMA.js';
import { EnvelopeIndicator } from './overlay/Envelope.js';
import { TEMAIndicator } from './overlay/TEMA.js';
import { AwesomeOscillatorIndicator } from './panel/AwesomeOscillator.js';
import { ChaikinOscillatorIndicator } from './panel/ChaikinOscillator.js';
// Panels
import { RSIIndicator } from './panel/RSI.js';
import { MACDIndicator } from './panel/MACD.js';
import { StochasticIndicator } from './panel/Stochastic.js';
import { ATRIndicator } from './panel/ATR.js';
import { ADXIndicator } from './panel/ADX.js';
import { OBVIndicator } from './panel/OBV.js';
import { WilliamsRIndicator } from './panel/WilliamsR.js';
import { CCIIndicator } from './panel/CCI.js';
import { MFIIndicator } from './panel/MFI.js';
import { AroonIndicator } from './panel/Aroon.js';
import { ROCIndicator } from './panel/ROC.js';
import { TSIIndicator } from './panel/TSI.js';
import { CMFIndicator } from './panel/CMF.js';
import { VolumeDeltaIndicator } from './panel/VolumeDelta.js';
import { VortexIndicator } from './panel/Vortex.js';
import { ChoppinessIndexIndicator } from './panel/ChoppinessIndex.js';
import { UltimateOscillatorIndicator } from './panel/UltimateOscillator.js';
import { ForceIndexIndicator } from './panel/ForceIndex.js';
import { ConnorsRSIIndicator } from './panel/ConnorsRSI.js';
import { CoppockIndicator } from './panel/Coppock.js';
import { KSTIndicator } from './panel/KST.js';
import { ElderRayIndicator } from './panel/ElderRay.js';
import { SchaffTrendCycleIndicator } from './panel/SchaffTrendCycle.js';
import { KlingerIndicator } from './panel/Klinger.js';
import { FisherTransformIndicator } from './panel/FisherTransform.js';
import { DetrendedPriceOscillatorIndicator } from './panel/DetrendedPriceOscillator.js';
import { BalanceOfPowerIndicator } from './panel/BalanceOfPower.js';
import { MassIndexIndicator } from './panel/MassIndex.js';
import { ChandeMomentumIndicator } from './panel/ChandeMomentum.js';
import { TRIXIndicator } from './panel/TRIX.js';
import { EaseOfMovementIndicator } from './panel/EaseOfMovement.js';
import { PriceVolumeTrendIndicator } from './panel/PriceVolumeTrend.js';
import { WilliamsADIndicator } from './panel/WilliamsAD.js';
import { ChaikinVolatilityIndicator } from './panel/ChaikinVolatility.js';
import { RelativeVigorIndicator } from './panel/RelativeVigor.js';
import { StochasticRSIIndicator } from './panel/StochasticRSI.js';
import { PercentagePriceOscillatorIndicator } from './panel/PercentagePriceOscillator.js';
import { AcceleratorOscillatorIndicator } from './panel/AcceleratorOscillator.js';
import { RelativeMomentumIndexIndicator } from './panel/RelativeMomentumIndex.js';
import { DisparityIndexIndicator } from './panel/DisparityIndex.js';
import { QstickIndicator } from './panel/Qstick.js';
import { PrettyGoodOscillatorIndicator } from './panel/PrettyGoodOscillator.js';
import { StdDevIndicator } from './panel/StdDev.js';
import { VolumeProfileIndicator } from './panel/VolumeProfile.js';
import { AccumulationDistributionIndicator } from './panel/AccumulationDistribution.js';
import { VROCIndicator } from './panel/VROC.js';

import { DEMAIndicator } from './overlay/DEMA.js';
import { SMMAIndicator } from './overlay/SMMA.js';
import { ALMAIndicator } from './overlay/ALMA.js';
import { KAMAIndicator } from './overlay/KAMA.js';
import { LSMAIndicator } from './overlay/LSMA.js';
import { McGinleyDynamicIndicator } from './overlay/McGinleyDynamic.js';
import { MACrossIndicator } from './overlay/MACross.js';
import { WilliamsFractalsIndicator } from './overlay/WilliamsFractals.js';
import { ChandeKrollStopIndicator } from './overlay/ChandeKrollStop.js';
import { BollingerPercentBIndicator } from './panel/BollingerPercentB.js';
import { BollingerBandWidthIndicator } from './panel/BollingerBandWidth.js';
import { MomentumIndicator } from './panel/Momentum.js';
import { HistoricalVolatilityIndicator } from './panel/HistoricalVolatility.js';
import { VolumeOscillatorIndicator } from './panel/VolumeOscillator.js';
import { UlcerIndexIndicator } from './panel/UlcerIndex.js';
import { StochasticMomentumIndexIndicator } from './panel/StochasticMomentumIndex.js';
import { RelativeVolatilityIndexIndicator } from './panel/RelativeVolatilityIndex.js';
import { TrendStrengthIndexIndicator } from './panel/TrendStrengthIndex.js';
import { LinearRegressionSlopeIndicator } from './panel/LinearRegressionSlope.js';
import { StandardErrorIndicator } from './panel/StandardError.js';
import { AverageDayRangeIndicator } from './panel/AverageDayRange.js';
import { NetVolumeIndicator } from './panel/NetVolume.js';
import { StandardErrorBandsIndicator } from './overlay/StandardErrorBands.js';
import { GuppyMMAIndicator } from './overlay/GuppyMMA.js';
import { MARibbonIndicator } from './overlay/MARibbon.js';
import { AveragePriceIndicator, MedianPriceIndicator, TypicalPriceIndicator } from './overlay/PriceAverages.js';
import { MAChannelIndicator } from './overlay/MAChannel.js';
import { HammingMAIndicator } from './overlay/HammingMA.js';
import { MADoubleIndicator, MATripleIndicator } from './overlay/MovingAverageSets.js';
import { VolatilityIndexIndicator } from './overlay/VolatilityIndex.js';
import { AccumulativeSwingIndexIndicator } from './panel/AccumulativeSwingIndex.js';
import { AdvanceDeclineIndicator } from './panel/AdvanceDecline.js';
import { MajorityRuleIndicator } from './panel/MajorityRule.js';
import { ChopZoneIndicator } from './panel/ChopZone.js';
import { SMIErgodicIndicator } from './panel/SMIErgodic.js';
import { PriceOscillatorIndicator } from './panel/PriceOscillator.js';
import { VolatilityOHLCIndicator, VolatilityZeroTrendIndicator } from './panel/VolatilityEstimators.js';

export function registerBuiltInIndicators(engine: IndicatorEngine): void {
  // Overlays
  engine.register(new SMAIndicator());
  engine.register(new EMAIndicator());
  engine.register(new BollingerBandsIndicator());
  engine.register(new VWAPIndicator());
  engine.register(new IchimokuIndicator());
  engine.register(new ParabolicSARIndicator());
  engine.register(new SupertrendIndicator());
  engine.register(new KeltnerChannelIndicator());
  engine.register(new DonchianChannelIndicator());
  engine.register(new PivotPointsIndicator());
  engine.register(new AnchoredVWAPIndicator());
  engine.register(new ZigZagIndicator());
  engine.register(new LinearRegressionChannelIndicator());
  engine.register(new HullMAIndicator());
  engine.register(new MTFMovingAverageIndicator());
  engine.register(new SessionVWAPIndicator());
  engine.register(new ChandelierExitIndicator());
  engine.register(new AlligatorIndicator());
  engine.register(new VWMAIndicator());
  engine.register(new WMAIndicator());
  engine.register(new EnvelopeIndicator());
  engine.register(new TEMAIndicator());
  // Panels
  engine.register(new RSIIndicator());
  engine.register(new MACDIndicator());
  engine.register(new StochasticIndicator());
  engine.register(new ATRIndicator());
  engine.register(new ADXIndicator());
  engine.register(new OBVIndicator());
  engine.register(new WilliamsRIndicator());
  engine.register(new CCIIndicator());
  engine.register(new MFIIndicator());
  engine.register(new AroonIndicator());
  engine.register(new ROCIndicator());
  engine.register(new TSIIndicator());
  engine.register(new CMFIndicator());
  engine.register(new StdDevIndicator());
  engine.register(new VolumeProfileIndicator());
  engine.register(new AccumulationDistributionIndicator());
  engine.register(new VROCIndicator());
  engine.register(new AwesomeOscillatorIndicator());
  engine.register(new ChaikinOscillatorIndicator());
  engine.register(new VolumeDeltaIndicator());
  engine.register(new VortexIndicator());
  engine.register(new ChoppinessIndexIndicator());
  engine.register(new UltimateOscillatorIndicator());
  engine.register(new ForceIndexIndicator());
  engine.register(new ConnorsRSIIndicator());
  engine.register(new CoppockIndicator());
  engine.register(new KSTIndicator());
  engine.register(new ElderRayIndicator());
  engine.register(new SchaffTrendCycleIndicator());
  engine.register(new KlingerIndicator());
  engine.register(new FisherTransformIndicator());
  engine.register(new DetrendedPriceOscillatorIndicator());
  engine.register(new BalanceOfPowerIndicator());
  engine.register(new MassIndexIndicator());
  engine.register(new ChandeMomentumIndicator());
  engine.register(new TRIXIndicator());
  engine.register(new EaseOfMovementIndicator());
  engine.register(new PriceVolumeTrendIndicator());
  engine.register(new WilliamsADIndicator());
  engine.register(new ChaikinVolatilityIndicator());
  engine.register(new RelativeVigorIndicator());
  engine.register(new StochasticRSIIndicator());
  engine.register(new PercentagePriceOscillatorIndicator());
  engine.register(new AcceleratorOscillatorIndicator());
  engine.register(new RelativeMomentumIndexIndicator());
  engine.register(new DisparityIndexIndicator());
  engine.register(new QstickIndicator());
  engine.register(new PrettyGoodOscillatorIndicator());
  engine.register(new DEMAIndicator());
  engine.register(new SMMAIndicator());
  engine.register(new ALMAIndicator());
  engine.register(new KAMAIndicator());
  engine.register(new LSMAIndicator());
  engine.register(new McGinleyDynamicIndicator());
  engine.register(new MACrossIndicator());
  engine.register(new WilliamsFractalsIndicator());
  engine.register(new ChandeKrollStopIndicator());
  engine.register(new BollingerPercentBIndicator());
  engine.register(new BollingerBandWidthIndicator());
  engine.register(new MomentumIndicator());
  engine.register(new HistoricalVolatilityIndicator());
  engine.register(new VolumeOscillatorIndicator());
  engine.register(new UlcerIndexIndicator());
  engine.register(new StochasticMomentumIndexIndicator());
  engine.register(new RelativeVolatilityIndexIndicator());
  engine.register(new TrendStrengthIndexIndicator());
  engine.register(new LinearRegressionSlopeIndicator());
  engine.register(new StandardErrorIndicator());
  engine.register(new AverageDayRangeIndicator());
  engine.register(new NetVolumeIndicator());
  engine.register(new StandardErrorBandsIndicator());
  engine.register(new GuppyMMAIndicator());
  engine.register(new MARibbonIndicator());
  engine.register(new AveragePriceIndicator());
  engine.register(new MedianPriceIndicator());
  engine.register(new TypicalPriceIndicator());
  engine.register(new MAChannelIndicator());
  engine.register(new HammingMAIndicator());
  engine.register(new MADoubleIndicator());
  engine.register(new MATripleIndicator());
  engine.register(new VolatilityIndexIndicator());
  engine.register(new AccumulativeSwingIndexIndicator());
  engine.register(new AdvanceDeclineIndicator());
  engine.register(new MajorityRuleIndicator());
  engine.register(new ChopZoneIndicator());
  engine.register(new SMIErgodicIndicator());
  engine.register(new PriceOscillatorIndicator());
  engine.register(new VolatilityOHLCIndicator());
  engine.register(new VolatilityZeroTrendIndicator());
}
