import type { IndicatorEngine } from './IndicatorEngine.js';
// Overlays
import { SMAIndicator } from './overlay/SMA.js';
import { EMAIndicator } from './overlay/EMA.js';
import { BollingerBandsIndicator } from './overlay/BollingerBands.js';
import { VWAPIndicator } from './overlay/VWAP.js';
import { IchimokuIndicator } from './overlay/Ichimoku.js';
import { ParabolicSARIndicator } from './overlay/ParabolicSAR.js';
import { SupertrendIndicator } from './overlay/Supertrend.js';
import { KeltnerChannelIndicator } from './overlay/KeltnerChannel.js';
import { DonchianChannelIndicator } from './overlay/DonchianChannel.js';
import { PivotPointsIndicator } from './overlay/PivotPoints.js';
import { AnchoredVWAPIndicator } from './overlay/AnchoredVWAP.js';
import { ZigZagIndicator } from './overlay/ZigZag.js';
import { LinearRegressionChannelIndicator } from './overlay/LinearRegressionChannel.js';
import { HullMAIndicator } from './overlay/HullMA.js';
import { MTFMovingAverageIndicator } from './overlay/MTFMovingAverage.js';
import { SessionVWAPIndicator } from './overlay/SessionVWAP.js';
import { ChandelierExitIndicator } from './overlay/ChandelierExit.js';
import { AlligatorIndicator } from './overlay/Alligator.js';
import { AwesomeOscillatorIndicator } from './panel/AwesomeOscillator.js';
import { ChaikinOscillatorIndicator } from './panel/ChaikinOscillator.js';
// Panels
import { RSIIndicator } from './panel/RSI.js';
import { MACDIndicator } from './panel/MACD.js';
import { StochasticIndicator } from './panel/Stochastic.js';
import { ATRIndicator } from './panel/ATR.js';
import { ADXIndicator } from './panel/ADX.js';
import { OBVIndicator } from './panel/OBV.js';
import { WilliamsRIndicator } from './panel/WilliamsR.js';
import { CCIIndicator } from './panel/CCI.js';
import { MFIIndicator } from './panel/MFI.js';
import { AroonIndicator } from './panel/Aroon.js';
import { ROCIndicator } from './panel/ROC.js';
import { TSIIndicator } from './panel/TSI.js';
import { CMFIndicator } from './panel/CMF.js';
import { VolumeDeltaIndicator } from './panel/VolumeDelta.js';
import { VortexIndicator } from './panel/Vortex.js';
import { ChoppinessIndexIndicator } from './panel/ChoppinessIndex.js';
import { UltimateOscillatorIndicator } from './panel/UltimateOscillator.js';
import { ForceIndexIndicator } from './panel/ForceIndex.js';
import { ConnorsRSIIndicator } from './panel/ConnorsRSI.js';
import { CoppockIndicator } from './panel/Coppock.js';
import { KSTIndicator } from './panel/KST.js';
import { ElderRayIndicator } from './panel/ElderRay.js';
import { SchaffTrendCycleIndicator } from './panel/SchaffTrendCycle.js';
import { KlingerIndicator } from './panel/Klinger.js';
import { FisherTransformIndicator } from './panel/FisherTransform.js';
import { DetrendedPriceOscillatorIndicator } from './panel/DetrendedPriceOscillator.js';
import { BalanceOfPowerIndicator } from './panel/BalanceOfPower.js';
import { MassIndexIndicator } from './panel/MassIndex.js';
import { ChandeMomentumIndicator } from './panel/ChandeMomentum.js';
import { TRIXIndicator } from './panel/TRIX.js';
import { EaseOfMovementIndicator } from './panel/EaseOfMovement.js';
import { PriceVolumeTrendIndicator } from './panel/PriceVolumeTrend.js';
import { WilliamsADIndicator } from './panel/WilliamsAD.js';
import { ChaikinVolatilityIndicator } from './panel/ChaikinVolatility.js';
import { RelativeVigorIndicator } from './panel/RelativeVigor.js';
import { StochasticRSIIndicator } from './panel/StochasticRSI.js';
import { StdDevIndicator } from './panel/StdDev.js';
import { VolumeProfileIndicator } from './panel/VolumeProfile.js';
import { AccumulationDistributionIndicator } from './panel/AccumulationDistribution.js';
import { VROCIndicator } from './panel/VROC.js';

export function registerBuiltInIndicators(engine: IndicatorEngine): void {
  // Overlays
  engine.register(new SMAIndicator());
  engine.register(new EMAIndicator());
  engine.register(new BollingerBandsIndicator());
  engine.register(new VWAPIndicator());
  engine.register(new IchimokuIndicator());
  engine.register(new ParabolicSARIndicator());
  engine.register(new SupertrendIndicator());
  engine.register(new KeltnerChannelIndicator());
  engine.register(new DonchianChannelIndicator());
  engine.register(new PivotPointsIndicator());
  engine.register(new AnchoredVWAPIndicator());
  engine.register(new ZigZagIndicator());
  engine.register(new LinearRegressionChannelIndicator());
  engine.register(new HullMAIndicator());
  engine.register(new MTFMovingAverageIndicator());
  engine.register(new SessionVWAPIndicator());
  engine.register(new ChandelierExitIndicator());
  engine.register(new AlligatorIndicator());
  // Panels
  engine.register(new RSIIndicator());
  engine.register(new MACDIndicator());
  engine.register(new StochasticIndicator());
  engine.register(new ATRIndicator());
  engine.register(new ADXIndicator());
  engine.register(new OBVIndicator());
  engine.register(new WilliamsRIndicator());
  engine.register(new CCIIndicator());
  engine.register(new MFIIndicator());
  engine.register(new AroonIndicator());
  engine.register(new ROCIndicator());
  engine.register(new TSIIndicator());
  engine.register(new CMFIndicator());
  engine.register(new StdDevIndicator());
  engine.register(new VolumeProfileIndicator());
  engine.register(new AccumulationDistributionIndicator());
  engine.register(new VROCIndicator());
  engine.register(new AwesomeOscillatorIndicator());
  engine.register(new ChaikinOscillatorIndicator());
  engine.register(new VolumeDeltaIndicator());
  engine.register(new VortexIndicator());
  engine.register(new ChoppinessIndexIndicator());
  engine.register(new UltimateOscillatorIndicator());
  engine.register(new ForceIndexIndicator());
  engine.register(new ConnorsRSIIndicator());
  engine.register(new CoppockIndicator());
  engine.register(new KSTIndicator());
  engine.register(new ElderRayIndicator());
  engine.register(new SchaffTrendCycleIndicator());
  engine.register(new KlingerIndicator());
  engine.register(new FisherTransformIndicator());
  engine.register(new DetrendedPriceOscillatorIndicator());
  engine.register(new BalanceOfPowerIndicator());
  engine.register(new MassIndexIndicator());
  engine.register(new ChandeMomentumIndicator());
  engine.register(new TRIXIndicator());
  engine.register(new EaseOfMovementIndicator());
  engine.register(new PriceVolumeTrendIndicator());
  engine.register(new WilliamsADIndicator());
  engine.register(new ChaikinVolatilityIndicator());
  engine.register(new RelativeVigorIndicator());
  engine.register(new StochasticRSIIndicator());
}
