export { TrendLineTool } from './TrendLine.js';
export { HorizontalLineTool } from './HorizontalLine.js';
export { HorizontalRayTool } from './HorizontalRay.js';
export { VerticalLineTool } from './VerticalLine.js';
export { RayTool } from './Ray.js';
export { ExtendedLineTool } from './ExtendedLine.js';
export { ParallelChannelTool } from './ParallelChannel.js';
export { RegressionChannelTool } from './RegressionChannel.js';
export { FibRetracementTool } from './FibRetracement.js';
export { FibExtensionTool } from './FibExtension.js';
export { RectangleTool } from './Rectangle.js';
export { EllipseTool } from './Ellipse.js';
export { TriangleTool } from './Triangle.js';
export { PitchforkTool } from './Pitchfork.js';
export { ElliottWaveTool } from './ElliottWave.js';
export { PriceRangeTool } from './PriceRange.js';
export { DateRangeTool } from './DateRange.js';
export { MeasureTool } from './Measure.js';
export { TextAnnotationTool } from './TextAnnotation.js';
export { ArrowTool } from './Arrow.js';
export { GannFanTool } from './GannFan.js';
export { GannBoxTool } from './GannBox.js';
export { AnchoredVWAPTool } from './AnchoredVWAP.js';
export { VolumeProfileRangeTool } from './VolumeProfileRange.js';
export { FibTimeZonesTool } from './FibTimeZones.js';
export { RiskRewardTool } from './RiskReward.js';
export { CrossLineTool } from './CrossLine.js';
export { TrendAngleTool } from './TrendAngle.js';
export { InfoLineTool } from './InfoLine.js';
export { FibChannelTool } from './FibChannel.js';
export { FibSpeedResistanceFanTool } from './FibSpeedResistanceFan.js';
export { SchiffPitchforkTool, ModifiedSchiffPitchforkTool } from './Pitchfork.js';
export { XABCDPatternTool, ABCDPatternTool, HeadAndShouldersTool } from './patterns.js';
export { CircleTool } from './Circle.js';
export { DateAndPriceRangeTool } from './DateAndPriceRange.js';
export { CyclicLinesTool } from './CyclicLines.js';
export { PriceLabelTool } from './PriceLabel.js';

import type { DrawingManager } from '../DrawingManager.js';
import { TrendLineTool } from './TrendLine.js';
import { HorizontalLineTool } from './HorizontalLine.js';
import { HorizontalRayTool } from './HorizontalRay.js';
import { VerticalLineTool } from './VerticalLine.js';
import { RayTool } from './Ray.js';
import { ExtendedLineTool } from './ExtendedLine.js';
import { ParallelChannelTool } from './ParallelChannel.js';
import { RegressionChannelTool } from './RegressionChannel.js';
import { FibRetracementTool } from './FibRetracement.js';
import { FibExtensionTool } from './FibExtension.js';
import { RectangleTool } from './Rectangle.js';
import { EllipseTool } from './Ellipse.js';
import { TriangleTool } from './Triangle.js';
import { PitchforkTool, SchiffPitchforkTool, ModifiedSchiffPitchforkTool } from './Pitchfork.js';
import { ElliottWaveTool } from './ElliottWave.js';
import { PriceRangeTool } from './PriceRange.js';
import { DateRangeTool } from './DateRange.js';
import { MeasureTool } from './Measure.js';
import { TextAnnotationTool } from './TextAnnotation.js';
import { ArrowTool } from './Arrow.js';
import { GannFanTool } from './GannFan.js';
import { GannBoxTool } from './GannBox.js';
import { AnchoredVWAPTool } from './AnchoredVWAP.js';
import { VolumeProfileRangeTool } from './VolumeProfileRange.js';
import { FibTimeZonesTool } from './FibTimeZones.js';
import { RiskRewardTool } from './RiskReward.js';
import { CrossLineTool } from './CrossLine.js';
import { TrendAngleTool } from './TrendAngle.js';
import { InfoLineTool } from './InfoLine.js';
import { FibChannelTool } from './FibChannel.js';
import { FibSpeedResistanceFanTool } from './FibSpeedResistanceFan.js';
import { XABCDPatternTool, ABCDPatternTool, HeadAndShouldersTool } from './patterns.js';
import { CircleTool } from './Circle.js';
import { DateAndPriceRangeTool } from './DateAndPriceRange.js';
import { CyclicLinesTool } from './CyclicLines.js';
import { PriceLabelTool } from './PriceLabel.js';

export function registerBuiltInDrawingTools(manager: DrawingManager): void {
  manager.register(new TrendLineTool());
  manager.register(new HorizontalLineTool());
  manager.register(new HorizontalRayTool());
  manager.register(new VerticalLineTool());
  manager.register(new RayTool());
  manager.register(new ExtendedLineTool());
  manager.register(new ParallelChannelTool());
  manager.register(new RegressionChannelTool());
  manager.register(new FibRetracementTool());
  manager.register(new FibExtensionTool());
  manager.register(new RectangleTool());
  manager.register(new EllipseTool());
  manager.register(new TriangleTool());
  manager.register(new PitchforkTool());
  manager.register(new ElliottWaveTool());
  manager.register(new PriceRangeTool());
  manager.register(new DateRangeTool());
  manager.register(new MeasureTool());
  manager.register(new TextAnnotationTool());
  manager.register(new ArrowTool());
  manager.register(new GannFanTool());
  manager.register(new GannBoxTool());
  manager.register(new AnchoredVWAPTool());
  manager.register(new VolumeProfileRangeTool());
  manager.register(new FibTimeZonesTool());
  manager.register(new RiskRewardTool());
  manager.register(new CrossLineTool());
  manager.register(new TrendAngleTool());
  manager.register(new InfoLineTool());
  manager.register(new FibChannelTool());
  manager.register(new FibSpeedResistanceFanTool());
  manager.register(new SchiffPitchforkTool());
  manager.register(new ModifiedSchiffPitchforkTool());
  manager.register(new XABCDPatternTool());
  manager.register(new ABCDPatternTool());
  manager.register(new HeadAndShouldersTool());
  manager.register(new CircleTool());
  manager.register(new DateAndPriceRangeTool());
  manager.register(new CyclicLinesTool());
  manager.register(new PriceLabelTool());
}
