// Docs that AI tools and the docs site read, generated from the code so they
// cannot drift from it:
//   demo/src/lib/generated/indicators.json        the docs site's indicator catalog
//   skills/tradecanvas/references/indicators.md   the agent skill's indicator reference
//   demo/static/llms.txt, demo/static/llms-full.txt
//   packages/library/README.md                    the npm page: the root README, links made absolute
//
//   node scripts/gen-ai-docs.mjs           write them (after `pnpm build`)
//   node scripts/gen-ai-docs.mjs --check   fail if any is out of date
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://bonguynvan.github.io/tradecanvas';
const REPO = 'https://github.com/bonguynvan/tradecanvas';
const check = process.argv.includes('--check');

const core = await import(pathToFileURL(join(ROOT, 'packages/core/dist/index.js')).href);
const engine = new core.IndicatorEngine();
core.registerBuiltInIndicators(engine);
const descriptors = engine.getAvailableIndicators();

/** The catalog: each built-in indicator's id, name, inputs, lines and levels. */
const catalog = descriptors.map((d) => ({
  id: d.id,
  name: d.name,
  shortName: d.shortName ?? d.id.toUpperCase(),
  placement: d.placement,
  params: d.defaultConfig,
  ...(d.inputs ? { inputs: d.inputs } : {}),
  plots: (d.plots ?? []).map((p) => ({ key: p.key, title: p.title, kind: p.kind ?? 'line' })),
  ...(d.levels?.length ? { levels: d.levels } : {}),
  ...(d.scale ? { scale: d.scale } : {}),
}));

const cell = (s) => String(s).replace(/\|/g, '\\|');
const paramsText = (params) => Object.entries(params).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join(', ') || '—';
const sourceNote = (ind) => (ind.inputs && Object.values(ind.inputs).some((i) => i.source) ? ' ✓' : '');

function indicatorsMarkdown() {
  const section = (placement, title, blurb) => {
    const rows = catalog.filter((i) => i.placement === placement);
    return [
      `## ${title} (${rows.length})`,
      '',
      blurb,
      '',
      '| id | Name | Default params | Lines (key: title) | Levels | Source |',
      '|---|---|---|---|---|---|',
      ...rows.map((i) => `| \`${i.id}\` | ${cell(i.name)} | ${cell(paramsText(i.params))} | ${cell(i.plots.map((p) => `${p.key}: ${p.title}`).join(', ') || '—')} | ${i.levels?.join(', ') ?? '—'} |${sourceNote(i)} |`),
      '',
    ].join('\n');
  };
  return [
    '<!-- Generated by scripts/gen-ai-docs.mjs from the indicator registry. Do not edit by hand. -->',
    '',
    '# Built-in indicators',
    '',
    `${catalog.length} indicators. Add one with \`chart.addIndicator(id, params)\`; params you leave out take the defaults below.`,
    'An indicator\'s values at bar `i` are `chart.getIndicatorOutput(instanceId).series[i]`, an object keyed by the line keys listed here.',
    '"Source ✓" means it has a `source` input: a price (`close`, `open`, `high`, `low`, `hl2`, `hlc3`, `ohlc4`, `hlcc4`) or another indicator\'s line (`indicatorSource(instanceId, key)`).',
    '',
    section('overlay', 'On the price pane', 'Drawn over the candles, on the price scale.'),
    section('panel', 'In a pane of their own', 'Drawn in a pane under the chart (`addIndicator(id, params, \'bottom\' | \'top\')`), with their own scale and levels.'),
  ].join('\n');
}

function llmsTxt() {
  return [
    '# TradeCanvas',
    '',
    '> Trading chart library for the web, drawn with Canvas 2D or WebGL (TypeScript, no runtime dependencies): candlestick, Heikin-Ashi, Renko and other chart types, '
      + `${catalog.length} indicators, drawing tools, live exchange feeds, orders and positions on the chart, alerts, replay and backtesting. `
      + 'npm: @tradecanvas/chart (Chart and the ChartWidget UI), @tradecanvas/react, @tradecanvas/vue, @tradecanvas/svelte, @tradecanvas/analytics.',
    '',
    'Use `ChartWidget` (`@tradecanvas/chart/widget`) for a complete trading UI, or `Chart` (`@tradecanvas/chart`) to build your own around it. '
      + 'Both need a sized DOM element and run in the browser only.',
    '',
    '## Docs',
    '',
    `- [Getting started](${SITE}/docs/getting-started): install, the widget, the headless chart`,
    `- [API reference](${SITE}/docs/api): Chart and ChartWidget methods, options and events`,
    `- [Indicators](${SITE}/docs/indicators): every built-in indicator with its id, inputs and lines`,
    `- [Styling](${SITE}/docs/styling): the widget's look as tokens: the Studio, Terminal and Capsule presets, your own theme, CSS variables`,
    `- [Customization](${SITE}/docs/customization): every way to customise: themes, looks, style overrides, the widget's 112 feature switches, your own toolbar, sidebar, status bar, menu entries and shortcuts, your own CSS`,
    `- [Chart types](${SITE}/docs/chart-types): candlestick, Heikin-Ashi, Renko, Kagi, point & figure and more`,
    `- [Drawing tools](${SITE}/docs/drawing-tools): trend lines, Fibonacci, Gann, patterns, text`,
    `- [Realtime and replay](${SITE}/docs/realtime): data adapters (Binance, Coinbase, Bybit, Kraken, WebSocket, polling) and replay`,
    `- [Trading](${SITE}/docs/trading): orders, positions, brackets and execution adapters on the chart`,
    `- [Frameworks](${SITE}/docs/frameworks): React, Vue and Svelte components`,
    `- [Plugins](${SITE}/docs/plugins): custom indicators, drawings and chart types`,
    `- [Analytics](${SITE}/docs/analytics): strategy backtester and risk metrics`,
    '',
    '## Agent skill',
    '',
    `- [SKILL.md](${REPO}/blob/main/skills/tradecanvas/SKILL.md): how to build with TradeCanvas, the rules that avoid most bugs, worked examples`,
    `- [Indicator reference](${REPO}/blob/main/skills/tradecanvas/references/indicators.md): ids, default params, lines and levels`,
    `- [Recipes](${REPO}/blob/main/skills/tradecanvas/references/recipes.md): live data, custom adapters, indicators on indicators, custom indicators, layouts`,
    '',
    '## Optional',
    '',
    `- [Everything in one file](${SITE}/llms-full.txt): the library README, the skill and its references`,
    `- [Source](${REPO})`,
    '',
  ].join('\n');
}

/**
 * The README npm shows: the root one, with its relative links and images made
 * absolute, since npm has no repository to resolve them against.
 */
function npmReadme() {
  const RAW = 'https://raw.githubusercontent.com/bonguynvan/tradecanvas/main';
  const ABSOLUTE = /^([a-z][a-z0-9+.-]*:|#|\/\/)/i;
  const absolute = (url) => {
    if (ABSOLUTE.test(url)) return url;
    const path = url.replace(/^\.?\//, '');
    if (/\.(png|jpe?g|gif|svg|webp)$/i.test(path.split(/[?#]/)[0])) return `${RAW}/${path}`;
    return `${REPO}/${path.endsWith('/') ? 'tree' : 'blob'}/main/${path}`;
  };
  // Link targets `](url)` (with an optional <> and title) and src/href attributes.
  const LINK = /\]\((<?)([^)\s>]+)(>?)(\s+"[^"]*")?\)/g;
  const ATTR = /(?<![\w-])(src|href)="([^"]+)"/g;
  const rewrite = (text) => text
    .replace(LINK, (_, lt, url, gt, title = '') => `](${lt}${absolute(url)}${gt}${title})`)
    .replace(ATTR, (_, attr, url) => `${attr}="${absolute(url)}"`);
  // Code (fenced blocks, inline spans) is left as written: `handlers[type](event)` isn't a link.
  const CODE = /(```[\s\S]*?```|`[^`\n]*`)/;
  const prose = (md) => md.split(CODE).filter((_, i) => i % 2 === 0).join('\n');
  const readme = readFileSync(join(ROOT, 'README.md'), 'utf8').replace(/\r\n/g, '\n');
  const out = readme.split(CODE).map((part, i) => (i % 2 ? part : rewrite(part))).join('');
  const left = [...prose(out).matchAll(LINK)].map((m) => m[2])
    .concat([...prose(out).matchAll(ATTR)].map((m) => m[2]))
    .filter((url) => !ABSOLUTE.test(url));
  if (left.length) throw new Error(`relative links left in the npm README: ${left.join(', ')}`);
  return out;
}

function llmsFullTxt(indicatorsMd, readmeMd) {
  const read = (rel) => readFileSync(join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n').trim();
  const part = (title, body) => `\n\n${'='.repeat(78)}\n${title}\n${'='.repeat(78)}\n\n${body}`;
  return [
    llmsTxt().trim(),
    part('skills/tradecanvas/SKILL.md', read('skills/tradecanvas/SKILL.md')),
    part('skills/tradecanvas/references/recipes.md', read('skills/tradecanvas/references/recipes.md')),
    part('skills/tradecanvas/references/indicators.md', indicatorsMd.trim()),
    part('packages/library/README.md', readmeMd.trim()),
  ].join('') + '\n';
}

const indicatorsMd = indicatorsMarkdown();
const readmeMd = npmReadme();
const outputs = [
  ['demo/src/lib/generated/indicators.json', JSON.stringify(catalog, null, 2) + '\n'],
  ['skills/tradecanvas/references/indicators.md', indicatorsMd],
  ['demo/static/llms.txt', llmsTxt()],
  ['demo/static/llms-full.txt', llmsFullTxt(indicatorsMd, readmeMd)],
  ['packages/library/README.md', readmeMd],
];

let stale = 0;
for (const [rel, content] of outputs) {
  const path = join(ROOT, rel);
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) continue;
  if (check) {
    console.error(`out of date: ${rel} (run \`pnpm docs:gen\`)`);
    stale++;
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${rel}`);
}
if (stale) process.exit(1);
if (check) console.log(`AI docs up to date (${catalog.length} indicators)`);
